name: Build app

on: [push]

jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.11.1.1105

      - name: Run tests
        run: clojure -M:test
        shell: bash

      - name: Build app
        run: clojure -T:build uber
        shell: bash
