name: Build app

on: [push]

jobs:
  clojure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@5.0
        with:
          cli: 1.11.1.1105

      - name: Install clojure linter
        uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2020.04.05'

      - name: Run tests
        run: clojure -M:test
        shell: bash

      - name: Lint sources
        run: clj-kondo --lint src

      - name: Build app
        run: clojure -T:build uber
        shell: bash

      - name: Publish artifact
        uses: actions/upload-artifact@v3
        with:
          name: calculator.jar
          path: backend/target/calculator.jar
          if-no-files-found: error
