name: Build app

on: [push]

jobs:
  clojure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: backend/target/calculator.jar
          key: calculator-${{ github.sha }}.jar

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.3
        with:
          cli: 1.11.1.1149
          clj-kondo: 2022.06.22

      - name: Run tests
        run: clojure -M:test
        shell: bash

      - name: Lint sources
        run: clj-kondo --lint src

      - name: Build app
        run: clojure -T:build uber
        shell: bash
