name: System tests

on:
  workflow_run:
    workflows: ["Build app"]
    types:
      - completed

jobs:
  clojure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: calculator.jar

      - name: Test
        run: |
          echo "Local path"
          pwd
          echo "list files"
          ls -al
          echo "list files in workspace"
          ls -al ${{ github.workspace }}
