name: System tests

on:
  workflow_run:
    workflows: ["Build app"]
    types:
      - completed

jobs:
  clojure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: backend/target/calculator.jar
          key: calculator.jar

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@9.3
        with:
          bb: 0.8.2

      - name: Run tests
        run:
          bb run-tests ../backend/target/calculator.jar
